new Vue({
    el:"#app",
    data:{
        brandList:[],//品牌集合,
        page:0,//当前页码
        pageSize:10,//一页有多少行数据
        total:100,//总记录数
        maxPage:10,//最大页码数
        brand:{//品牌信息
            name:"",//品牌名称
            firstChar:"",//首字母
        },
        selectedId:[],//选中id的集合
        searchBrand:{//品牌信息
            name:"",//品牌名称
            firstChar:"",//首字母
        },
    },
    methods:{
        //请求品牌集合数据
        findBrandAll(){
            axios.get("/brand/findBrandAll").then(res=>{//成功返回
                this.brandList=res.data;//赋值
            }).catch(err=>{//失败返回
                alert("请求失败")
            });
        },
        //分页查询
        pageHandler(page){
           this.page=page;
            axios.post("/brand/findPage?page="+this.page+"&pageSize="+this.pageSize,this.searchBrand).then(res=>{//成功返回
               this.total=res.data.total;
                this.brandList=res.data.rows;//赋值
            }).catch(err=>{//失败返回
                alert("请求失败")
            });
        },
        //添加品牌 && 更新品牌
        addBrand(){
            var url=null;
            if(this.brand.id==null){
                url="/brand/add";
            }else{
                url="/brand/update"
            }
            axios.post(url,this.brand).then(res=>{
                  if(res.data.success){
                        alert(res.data.message)
                        this.pageHandler(1);
                    }else{
                        alert(res.data.message);
                    }
              }).catch(err=>{
                  alert("请求失败")
              })
        },
        //根据id查询品牌
        findById(id){
            this.brand=[];//清空
            axios.get("/brand/findById?id="+id).then(res=>{
                this.brand=res.data;
            }).catch(err=>{
                alert("请求失败")
            })
        },
        deleteSelection(event,id){//记录选中id
            //判断checkbox是否为选中状态
            if(event.target.checked){//选中
                this.selectedId.push(id);
            }else{
                //未选中
               var idx= this.selectedId.indexOf(id);
               this.selectedId.splice(idx,1)//删除元素
            }
        },
        /*删除品牌*/
        deleteById(){
            axios.post("/brand/deleteById",Qs.stringify({id:this.selectedId},{indices:false})).then(res=>{
                if(res.data.success){
                    alert(res.data.message)
                    this.pageHandler(1);
                }else{
                    alert(res.data.message);
                }
            }).catch(err=>{
                alert("请求失败")
            })
        }
    },
    created(){
        this.pageHandler(1);//调用
    }
})